"""add 2 new cols to table users: email, hashed_password

Revision ID: df5d8745d366
Revises: 0a26eabedc44
Create Date: 2026-04-22 15:29:53.450077

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "df5d8745d366"
down_revision: Union[str, Sequence[str], None] = "0a26eabedc44"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("email", sa.String(length=100), nullable=False)
    )
    op.add_column(
        "users", sa.Column("hashed_password", sa.String(), nullable=False)
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(
        op.f("ix_users_user_id"), "users", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_user_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_column("users", "hashed_password")
    op.drop_column("users", "email")
    # ### end Alembic commands ###
