"""add composite indexes to refresh_tokens

Revision ID: fde07d773ba3
Revises: 80b8c52f0b27
Create Date: 2026-07-20 11:25:54.528479

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "fde07d773ba3"
down_revision: Union[str, Sequence[str], None] = "80b8c52f0b27"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_refresh_tokens_user_id_revoked",
        "refresh_tokens",
        ["user_id", "is_revoked"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_refresh_tokens_user_id_revoked", table_name="refresh_tokens"
    )
    # ### end Alembic commands ###
